# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Jake P Grainger
CodeOfConductContact: Jake P Grainger
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Jake P Grainger
MarkdownIndentation: 2
PackageName: SpatialMultitaper
PackageOwner: JakeGrainger
PackageUUID: 9e2dbb0b-aeb4-47f9-9d40-f5da6e8cc913
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
