mt_est = make_simple_example()
real(mt_est[1, 2]).estimate == real.(mt_est[1, 2].power)
imag(mt_est[1, 2]).estimate == imag.(mt_est[1, 2].power)
abs2(mt_est[1, 2]).estimate == abs2.(mt_est[1, 2].power)
abs(mt_est[1, 2]).estimate == abs.(mt_est[1, 2].power)
conj(mt_est[1, 2]).estimate == conj.(mt_est[1, 2].power)
log(abs(mt_est[1, 1])).estimate == log.(abs.(mt_est[1, 1].power))
exp(mt_est[1, 2]).estimate == exp.(mt_est[1, 2].power)

rot_est = rotational_estimate(mt_est, radii = range(0, 2, 5))
real(rot_est[1, 2]).estimate == real.(rot_est[1, 2].estimate)
imag(rot_est[1, 2]).estimate == imag.(rot_est[1, 2].estimate)
abs2(rot_est[1, 2]).estimate == abs2.(rot_est[1, 2].estimate)
abs(rot_est[1, 2]).estimate == abs.(rot_est[1, 2].estimate)
conj(rot_est[1, 2]).estimate == conj.(rot_est[1, 2].estimate)
log(abs(rot_est[1, 1])).estimate == log.(abs.(rot_est[1, 1].estimate))
exp(rot_est[1, 2]).estimate == exp.(rot_est[1, 2].estimate)
